---

- name: Set hostname
  hostname:
    name: izaro

- name: "Update apt package index"
  apt:
    update_cache: true

- name: "Update installed apt packages"
  apt:
    update_cache: false
    upgrade: full
