---

- name: Set hostname
  hostname:
    name: izaro

- name: "Update installed apt packages"
  apt:
    update_cache: true
    upgrade: full

- name: Install security tools
  apt:
    pkg:
      - fail2ban
      - firewalld
    state: present
