---

- name: Create temporary directory
  tempfile:
    state: directory
  register: tmp_dir

- name: Get temporary directory path
  set_fact:
    tmp_dir: "{{ tmp_dir.path }}"

- name: Get ingress-nginx manifest file
  get_url:
    url: https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/baremetal/deploy.yaml
    dest: "{{ tmp_dir }}/ingress-nginx.yaml"

- name: Create namespace for nginx-ingress
  k8s:
    name: ingress-nginx
    api_version: v1
    kind: Namespace
    state: present

- name: Deploy ingress-nginx
  local_action:
    module: k8s
    name: ingress-nginx
    src: "{{ tmp_dir }}/ingress-nginx.yaml"
    state: present

- name: Patch ingress-nginx
  k8s:
    api_version: v1
    kind: Deployment
    name: ingress-nginx-controller
    namespace: ingress-nginx
    state: present
    definition: |
      spec:
        template:
          spec:
            hostNetwork: true

- name: Remove temporary directory
  file:
    state: absent
    path: "{{ tmp_dir }}"
