---

- name: Create volume
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    state: present
  when: (item.action == "create_empty") or
        (item.action == "create_and_copy")
  loop: "{{ kube.volumes }}"

- name: Managing volumes
  block:

  - name: Copy files to volume"
    debug:
      msg: "Copy files to volume"

  - name: Create a container with a new data volume
    containers.podman.podman_container:
      name: volume-manager
      image: alpine
      state: started
      detach: no
      volume:
        - "{{ item.name }}:/volumes/{{ item.name }}"

  - name: Copy container contents
    command: "podman cp {{ item.src }} volume-manager:/volumes/{{ item.name }}"

  - name: Remove the hanging container
    containers.podman.podman_container:
      name: volume-manager
      state: absent

  when: item.action == "create_and_copy"
  loop: "{{ kube.volumes }}"


