###############################################
#  Role: app-manager/pod/recreate             #
#  Removes a pod and recreates it             #
#                                             #
#  Arguments:                                 #
#    - pod_name: Name of the pod to recreate  #
#    - kube_file: Path of the kube file       #
###############################################
---

- debug:
    msg:
      - "Recreate pod"
      - "Pod name: {{ pod_name }}"
      - "Kube file (localhost): {{ kube_file }}"

- name: Remove pod
  containers.podman.podman_pod:
    name: "{{ pod_name }}"
    state: absent

- name: Calling role app-manager/pod/create
  ansible.builtin.include_role:
    name: app-manager/pod/create
  # Role vars ommitted because role inherits vars
  # vars:
  #   kube_file: "{{ kube_file }}"

