---

- name: Set the app name
  set_fact:
    app_name: nginx-waf

- name: Calculate paths
  set_fact:
    app_root: "./deployments/{{ app_name }}"
    cnt_root: "./deployments/{{ app_name }}/cnt-fs"

- name: Copy the assets to the OCI host
  ansible.builtin.copy:
    src: ../assets/
    dest: "{{ app_root }}/"
    remote_src: no
    validate: /usr/bin/ls %s

- name: Deploy app
  containers.podman.podman_play:
    kube_file: "{{ app_root }}/kube-file.yaml"
    recreate: true
    state: started
