###################################################
#  Role: app-manager/volume/copy                  #
#  Copies files from host to volume               #
#                                                 #
#  Arguments:                                     #
#    - name: Name of the volume                   #
#    - type: True if volume must be kept empty    #
#    - src: Source path to copy files from        #
#    - dst: Destination path for copied files     #
###################################################
---

- debug:
    msg:
      - "Copy content to volume"
      - "Volume name: {{ name }}"
      - "Volume type: {{ type }}"
      - "Content source (localhost): {{ src }}"
      - "Content desination (OCI host): {{ dst }}"

- block:

  - name: Create the bind-mount directory in the OCI host
    file:
      path: "{{ dst | dirname }}"
      state: directory

  - name: Copy the bind-mount contents to the OCI host
    ansible.builtin.copy:
      src: "{{ src }}"
      dest: "{{ dst }}"
      remote_src: no
      validate: /usr/bin/ls %s

  when: type == "bind"

- block:

  - name: Copy volume contents from Ansible Controller to OCI host
    ansible.builtin.copy:
      src: "{{ src }}"
      dest: "{{ dst }}"
      remote_src: no
      validate: /usr/bin/ls %s

  - name: Create the container to copy content to the volume
    containers.podman.podman_container:
      name: volume-manager
      image: alpine
      state: started
      detach: no
      volume:
        - "{{ name }}:/volumes/{{ name }}"

  - name: Copy volume contents from OCI host to the volume
    command: "podman cp {{ dst }}/. volume-manager:/volumes/{{ name }}"

  - name: Remove the container
    containers.podman.podman_container:
      name: volume-manager
      state: absent

  - name: Remove the copied volume files
    file:
      state: absent
      path: "{{ dst }}"

  when: type == "named"
