#############################################
#  Role: app-manager/web/open               #
#  Deploys apps                             #
#                                           #
#  Arguments:                               #
#    - app_name: Name of the app to open web access to  #
#############################################
---

- debug:
    msg:
      - "Open web access"
      - "App name: {{ app_name }}"

- name: Call role app-manager/volume/copy
  ansible.builtin.include_role:
    name: app-manager/volume/copy
  vars:
    name: "nginx-waf_nginx-conf-dir"
    type: "named"
    src: "{{ playbook_dir }}/../deployments/{{ app_name }}/conf/nginx-waf/"
    dst: "./deployments/{{ app_name }}/conf/nginx-waf"

- name: Call role app-manager/pod/recreate
  ansible.builtin.include_role:
    name: app-manager/pod/recreate
  vars:
    pod_name: "nginx-waf-pod-0"
    kube_file: "{{ playbook_dir }}/../deployments/nginx-waf/kube-file.yaml"
