---

- name: Set if present or absent
  set_fact:
    state: present

- name: "Add Helm repository: prometheus-community"
  kubernetes.core.helm_repository:
      name: prometheus-community
      repo_url: https://prometheus-community.github.io/helm-charts

- name: Read values.yaml
  set_fact:
    values: "{{lookup('ansible.builtin.file', './values.yaml') | from_yaml }}"

# - name: Read ingress.yaml
  # set_fact:
#     ingress: "{{lookup('ansible.builtin.file', './ingress.yaml') | from_yaml }}"

- name: "Create namespace: monitoring"
  k8s:
    name: monitoring
    kind: Namespace
    state: "{{ state }}"

- name: Install prometheus
  kubernetes.core.helm:
    name: prometheus
    namespace: monitoring
    chart_ref: prometheus-community/kube-prometheus-stack
    release_values: "{{ values }}"
    state: "{{ state }}"
  register: result

- name: Helm chart result
  debug:
    msg: "{{ result.stdout_lines }}"

# - name: Deploy ingress
  # k8s:
  #   state: "{{ state }}"
#     definition: "{{ ingress }}"
