---

- block:

  - name: Create the bind-mount directory in the OCI host
    file:
      path: "{{ item.dst | dirname }}"
      state: directory
    when: item.action == 'copy_bind_file'

  - name: Copy the bind-mount contents to the OCI host
    ansible.builtin.copy:
      src: "{{ item.src }}"
      dest: "{{ item.dst }}"
      remote_src: no
      validate: /usr/bin/ls %s

  when: item.type == 'bind'

- name: Copy volume contents from Ansible Controller to OCI host
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dst }}"
    remote_src: no
    validate: /usr/bin/ls %s

- name: Create named volume
  containers.podman.podman_volume:
    name: "{{ item.name }}"
    state: present
  when: item.type == 'named'

- block:

  - name: Create the container to copy content to the volume
    containers.podman.podman_container:
      name: volume-manager
      image: alpine
      state: started
      detach: no
      volume:
        - "{{ item.name }}:/volumes/{{ item.name }}"

  - name: Copy volume contents from OCI host to the volume
    command: "podman cp {{ item.dst }}/. volume-manager:/volumes/{{ item.name }}"

  - name: Remove the hanging container
    containers.podman.podman_container:
      name: volume-manager
      state: absent
  when:
  - item.type == 'named'
  - item.action == "create_named_and_copy"
