---

- name: Deploy WAF
  hosts: oci_host
  gather_facts: no
  become: no
  roles:
  - role: app-manager
    vars:
      app_name: nginx-waf
      app_src: "{{ playbook_dir }}/../deployments/nginx-waf"

# - name: Deploy WAF
  # hosts: oci_host
  # gather_facts: no
  # become: no
  # roles:
  # - role: app-manager
  #   vars:
  #     app_name: nginx-be
#       app_src: "{{ playbook_dir }}/../deployments/nginx-be"
