---
- hosts: 127.0.0.1
  tasks:
  - name: Getting volume infro from the kube file
    kube_file_info:
      kube_file: '../deployments/nginx-waf/kube-file.yaml'
    register: kube

  - debug: 
      msg: "{{ item.name }} | {{ item.type }} | {{ item.src }} | {{ item.dst }}"
    loop: "{{ kube.volumes }}"
