---

- name: Check if helm is installed
  shell: "which helm | wc -l"
  register: is_installed
  ignore_errors: yes

- block:
  - name: Install Helm
    shell:
      cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

  - name: "Add Helm repository: Helm (stable)"
    kubernetes.core.helm_repository:
      name: stable
      repo_url: https://charts.helm.sh/stable

  - name: Install Helm Plugin
    kubernetes.core.helm_plugin:
      plugin_path: https://github.com/databus23/helm-diff
      state: present

  when: is_installed.stdout == "0"
# - name: Set Helm chart values for nginx-ingress deployment
#   shell: |
#     echo "
#     controller:
#       config:
#         enable-modsecurity: \"true\"
#         enable-owasp-modsecurity-crs: \"true\"
#     " > ./helm-values.yml
# - name: Create temporary file
#   tempfile:
#     state: directory
#   register: tmp_dir
 
