version: "3.9"
   
services:
  nginx-waf:
    image: docker.io/nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "8080:80"
    environment:
    - ADMIN_NAME=Joseba
    - ADMIN_MAIL=josebamail
