---

- name: Install podman
  apt:
    pkg:
      - podman
      - python3
      - python3-dev
      - python3-pip
    state: present
    update_cache: yes

# - name: "Create podman network: production"
#   containers.podman.podman_network:
#     name: prod
