---

# - name: Install podman
  # apt:
  #   pkg:
  #     - podman
  #     - python3
  #     - python3-dev
  #     - python3-pip
  #   state: present
#     update_cache: yes

- name: Add Docker apt repository's GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  ansible.builtin.apt:
    name: 
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin

- name: Redirect port 80 to 8080 with Rich Rule
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 forward-port port=80 protocol=tcp to-port=8080
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

- name: Redirect port 443 to 8443 with Rich Rule
  ansible.posix.firewalld:
    rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
    zone: public
    permanent: yes
    immediate: yes
    state: enabled

# - name: "Create podman network: production"
  # containers.podman.podman_network:
  #   name: production
#     state: present
