---

- name: Copy the assets to the OCI host
  ansible.builtin.copy:
    src: "{{ app_src }}/"
    dest: "{{ dpl_base }}/{{ app_name }}/"
    remote_src: no
    validate: /usr/bin/ls %s

- name: Deploy app
  containers.podman.podman_play:
    kube_file: "{{ dpl_base }}/{{ app_name }}/kube-file.yaml"
    network: production
    recreate: true
    state: started
